config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, param: :taxon_id, only: [:show] do
      collection do
        get 'color'
        get 'size'
        get 'sort'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionValue.class_eval do
  scope :presentation, ->(name) do
    includes(:option_type).
    where(spree_option_types: {presentation: name}).
    pluck(:presentation).
    uniq
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :with_price_and_images, -> do
    includes([master: [:default_price, :images]])
  end
  scope :related_products, -> (taxon_ids) do
    joins(:taxons).where("spree_taxons.id IN (?)", taxon_ids).distinct
  end
  scope :except_main_product, -> (product_id) { where.not(id: product_id) }
  scope :with_value, -> (presentation) do
    includes(variants_including_master: :option_values).
    where(spree_option_values: {presentation: presentation})
  end
  scope :descend_by_available, -> do
    order(available_on: "DESC")
  end
  scope :ascend_by_available, -> do
    order(available_on: "ASC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :set_valiables

  def set_valiables
    @taxonomies = Spree::Taxonomy.all.includes(root: :children)
    @colors = Spree::OptionValue.presentation("Color")
    @sizes = Spree::OptionValue.presentation("Size")
  end

  def show
    @taxon = Spree::Taxon.find(params[:taxon_id])
    @category = @taxon.name
    @products = @taxon.all_products.includes(master: [:default_price, :images])
  end

  def color
    @category = "Color - " + params[:color]
    @products = Spree::Product.
    with_price_and_images.
    with_value(params[:color])
    render 'potepan/categories/show'
  end

  def size
    @category = "Size - " + params[:size]
    @products = Spree::Product.
    with_price_and_images.
    with_value(params[:size])
    render 'potepan/categories/show'
  end

  def sort
  @category = "Sort - " + params[:sort]
  sort_by(params[:sort])
  p params[:sort]
  end

  def seach
    
  end

  private
    def sort_by(params)
      case params
      when "descend_by_available"
        p "1"
        @products = Spree::Product.
        with_price_and_images.
        descend_by_available
      when "ascend_by_available"
        p "2"
        @products = Spree::Product.
        with_price_and_images.
        ascend_by_available
      when "descend_by_price"
        p "3"
        @products = Spree::Product.
        with_price_and_images.
        descend_by_master_price
      when "ascend_by_price"
        p "4"
        @products = Spree::Product.
        with_price_and_images.
        ascend_by_master_price
      end
    end

end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    taxon_ids = @product.taxon_ids
    @products = Spree::Product.
      includes([master: [:default_price, :images]]).
      except_main_product(@product.id).
      related_products(taxon_ids)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
    @new_products = Spree::Product.
    with_price_and_images.
    descend_by_available.limit(10)
  end

  def product_grid_left_sidebar
    @taxonomies = Spree::Taxonomy.includes([root: :children])
    @products = Spree::Product.includes([master: [:default_price, :images]])
  end

  def product_list_left_sidebar
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><%= yield(:title) %> - BIGBAG</title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
<!-- CUSTOM CSS -->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
<!-- TOPBAR -->
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form  id="form01" action="product-grid-left-sidebar.html" method="post">
              <li>
                <span class="input-group">
                  <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                  <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                </span>
              </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- NAVBAR -->
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="javascript:void(0)"><%= image_tag("logo.png") %></a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to 'Home', potepan_path %></li>
        <li class="dropdown megaDropMenu">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <form action="login-" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">メールアドレス</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">パスワード</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> 記憶しておく
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_blands_slide.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="owl-carousel partnersLogoSlider">
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
          </div>
        </div>
        <div class="slide">
          <div class="partnersLogo clearfix">
            <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_categories.html.erb
<li>
  <a href="javascript:;" data-toggle="collapse" data-target=<%= "##{taxonomy.id}" %>><%= taxonomy.name %><i class="fa fa-plus"></i></a>
  <ul id=<%= "#{taxonomy.id}" %> class="collapse collapseItem">
    <% if taxonomy.root.children.present? %>
      <% taxonomy.root.children.each do |taxon| %>
        <li>
          <%= link_to potepan_category_path(taxon.id) do %>
            <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>(<%= taxon.all_products.size %>)</span>
          <% end %>
        </li>
      <% end %>
    <% else %>
      <li>
        <%= link_to '#' do %>
          <i class="fa fa-caret-right" aria-hidden="true"></i>none<span>(0)</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/_category_lists.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <%= render partial: 'potepan/categories/categories', collection: @taxonomies, as: :taxonomy %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <%= render partial: 'potepan/categories/color_categories',collection: @colors, as: :color %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <%= render partial: 'potepan/categories/size_categories',collection: @sizes, as: :size %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_color_categories.html.erb
<li>
  <%= link_to color_potepan_categories_path(color: color) do %>
    <%= color %> <span>(<%= Spree::Product.with_value(color).size %>)</span>
  <% end %>
</li>

app/views/potepan/categories/_products_in_category.html.erb
<%= link_to potepan_product_path(product.id) do %>
  <div class="col-sm-4 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment.url(:large)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/categories/_size_categories.html.erb
<li>
  <%= link_to size_potepan_categories_path(size: size) do %>
    <%= size %> <span>(<%= Spree::Product.with_value(size).size %>)</span>
  <% end %>
</li>

app/views/potepan/categories/_sort_list.html.erb
<select name="guiest_id1" id="guiest_id1" class="select-drop">
  <option value="0" id="sort">並び替え</option>
  <option value="descend_by_available" id="sort">新着順</option>
  <option value="ascend_by_available" id="sort">古い順</option>
  <option value="descend_by_price" id="sort">高い順</option>
  <option value="ascend_by_price" id="sort">安い順</option>
</select>

app/views/potepan/categories/show.html.erb
<% provide(:title, "#{@category} - Category") %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2 id="category_title"><%= @category %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'home', potepan_path %>
            </li>
            <li>
              <a href="#">shop</a>
            </li>
            <li class="active"><%= @category %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <%= render 'potepan/categories/category_lists' %>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="row filterArea">
            <div class="col-xs-6">
              <%= render "potepan/categories/sort_list" %>
            </div>
            <div class="col-xs-6">
              <div class="btn-group pull-right" role="group">
                <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
                <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
              </div>
            </div>
          </div>
          <div class="row" id="pruducts_in_category">
            <% if @products.present? %>
              <%= render partial: 'potepan/categories/products_in_category', collection: @products, as: :product %>
            <% else %>
              <div class="no_items">
                <h2>NO Items....</h2>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix">
     <%= render 'potepan/categories/blands_slide' %>
  </section>
</div>

app/views/potepan/categories/sort.js.erb
$("#pruducts_in_category").html("<%= j(render partial: 'potepan/categories/products_in_category', collection: @products, as: :product) %>");

app/views/potepan/products/_product_imgs.html.erb
<div class="item <%= "active" if image_counter.zero? %>" data-thumb=<%= image_counter %> >
  <%= image_tag(image.attachment.url(:large)) %>
</div>

app/views/potepan/products/_product_imgs_thumb.html.erb
<div data-target="#carousel" data-slide-to=<%= "#{image_counter}" %> class="thumb">
  <%= image_tag(image.attachment.url(:small)) %>
</div>

app/views/potepan/products/_products.html.erb
<%= link_to potepan_product_path(product.id) do %>
  <div class="slide">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment.url(:small)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<%= link_to potepan_product_path(product.id) do %>
  <div class="slide">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment.url(:small)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="main-wrapper">

  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.slug %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'home', '/potepan/' %>
            </li>
            <li class="active"><%= @product.name %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>

  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                 <%= render partial: 'potepan/products/product_imgs', collection: @product.images, as: :image %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <%= render partial: 'potepan/products/product_imgs_thumb', collection: @product.images, as: :image %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li>
                  <%= link_to potepan_product_grid_left_sidebar_path do %>
                    <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                  <% end %>
                </li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <option value="0">S</option>
                  <option value="1">M</option>
                  <option value="2">L</option>
                  <option value="3">XL</option>
                </select>
              </span>
              <span class="quick-drop resizeWidth">
                <select name="guiest_id4" id="guiest_id4" class="select-drop">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </span>
              <div class="btn-area">
                <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row productsContent">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>関連商品</h4>
          </div>
        </div>
        <div class="col-xs-12 related_items">
          <% if @products.present? %>
            <div class="owl-carousel featuredProductsSlider">
              <%= render partial: 'potepan/products/products', collection: @products, as: :product %>
            </div>
          <% else %>
            <div class="no_items">
              <h2>No related Items....</h2>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>

</div>

app/views/potepan/sample/product_grid_left_sidebar.html.erb
<% provide(:title, "Category") %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2 id="category_title">Category</h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'home', potepan_path %>
            </li>
            <li>
              <a href="#">shop</a>
            </li>
            <li class="active">Category name</li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
          <div class="panel panel-default">
            <div class="panel-heading">商品カテゴリー</div>
            <div class="panel-body">
              <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
                <ul class="nav navbar-nav side-nav">
                  <%= render partial: 'potepan/categories/categories', collection: @taxonomies, as: :taxonomy %>
                </ul>
              </div>
            </div>
          </div>
          <div class="panel panel-default filterNormal">
            <div class="panel-heading">色から探す</div>
            <div class="panel-body">
              <ul class="list-unstyled">
                <li><a href="#">ブラック<span>(15)</span></a></li>
                <li><a href="#">ホワイト<span>(10)</span></a></li>
                <li><a href="#">レッド<span>(7)</span></a></li>
                <li><a href="#">ブルー<span>(12)</span></a></li>
                <li><a href="#">オレンジ<span>(12)</span></a></li>
              </ul>
            </div>
          </div>
          <div class="panel panel-default filterNormal">
            <div class="panel-heading">サイズから探す</div>
            <div class="panel-body">
              <ul class="list-unstyled clearfix">
                <li><a href="#">S<span>(15)</span></a></li>
                <li><a href="#">M<span>(10)</span></a></li>
                <li><a href="#">L<span>(7)</span></a></li>
                <li><a href="#">XL<span>(12)</span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="row filterArea">
            <div class="col-xs-6">
              <select name="guiest_id1" id="guiest_id1" class="select-drop">
                <option value="0">並び替え</option>
                <option value="1">人気順</option>
                <option value="2">安い順</option>
                <option value="3">新着順</option>
                <option value="3">高い順</option>
              </select>
            </div>
            <div class="col-xs-6">
              <div class="btn-group pull-right" role="group">
                <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
                <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
              </div>
            </div>
          </div>
          <div class="row" id="pruducts_in_category">
            <% if @products.present? %>
              <%= render partial: 'potepan/categories/products_in_category', collection: @products, as: :product %>
            <% else %>
              <div class="no_item">
                <h2>NO Items....</h2>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </section>
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="owl-carousel partnersLogoSlider">
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
              </div>
            </div>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>